### ISSUE TITLE
No module named 'titanbot.tt2'

### ISSUE THREAD

**Issue by otavioreis** [becurrie/titanbot#73]
I just tried to use your bot, but when I ran the command to start it, I got an error.

C:\github\titanbot\titanbot\tt2\core>python run.py -start
Traceback (most recent call last):
  File "run.py", line 23, in <module>
    from titanbot.tt2.core.bot import Bot
ModuleNotFoundError: No module named 'titanbot.tt2'

**Comment by becurrie** [comment]
Hey @otavioreis, I looked into this. It's an issue that I never caught because I'm working with PyCharm IDE for development and it does some dynamic changes to my PYTHONPATH. So I haven't seen this one before.

I'm working on a fix now. If you use an IDE of some sort, you can get around it for the time being.

**Comment by becurrie** [comment]
I've pushed a fix up to master now. See commit fd15fefa2a00970fdc4e7aab747fb21a89be4e7c for details... I've tested all available commands currently and they're working in my terminal. I'm closing this now. Feel free to create another issue if needed!

**Comment by becurrie** [comment]
Resolved by fd15fefa2a00970fdc4e7aab747fb21a89be4e7c

**Comment by otavioreis** [comment]
thank you @becurrie I'll test it now.
